
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;net10.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MarkdownSnippets.MsBuild" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Office.Interop.Excel" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="ProjectFiles" PrivateAssets="all" />
    <PackageReference Include="Verify.DiffPlex" />
    <PackageReference Include="Verify.Nunit" VersionOverride="33.0.0-beta.3" />
    <PackageReference Include="Argon" />
    <PackageReference Include="DiffEngine" />
    <PackageReference Include="EmptyFiles" />
    <PackageReference Include="SimpleInfoName" />
    <PackageReference Include="Verify" VersionOverride="33.0.0-beta.3" />
    <PackageReference Include="Polyfill" PrivateAssets="all" />
    <ProjectReference Include="..\Verify.ClosedXml\Verify.ClosedXml.csproj" />
    <PackageReference Include="ProjectDefaults" PrivateAssets="all" />
    <Reference Include="System.Windows.Forms" Condition="'$(TargetFramework)' == 'net48'" />

    <None Update="sample.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>

    <None Update="sample_*.xlsx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>

    <None Remove="~$*" />
  </ItemGroup>
</Project>
